package lynx;

public class ITypes {
	public enum checkType { PERSON, ACCOUNT, STUDENT, TEACHER }; 
	public enum countType { ENROLLED, PEOPLE, STUDENTS, TEACHERS, STUDENT_GRADES, AVAILABLE_PEOPLE, SUBJECTS, COURSES, SUBJECT_CALENDAR,COURSES_CALENDAR, STUDENT_ENROLLMENT_COUNT, COURSE_ENROLLMENT_COUNT, ACCOUNTS, COURSES_FROM_SUBJECTS,COURSES_CALENDAR_STUDENT};
}
