IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Accounts')
BEGIN
    CREATE TABLE accounts
	(
		accountID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		personID INT NOT NULL,
		username VARCHAR(20),
		hash VARCHAR(500),
		salt VARCHAR(50),
		lastLogin DATE NULL
	)
END

