IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'division')
BEGIN
    CREATE TABLE division
	(
		divisionID  INT IDENTITY(1,1) PRIMARY KEY,
		alternateID INT NOT NULL,
		name VARCHAR(50) NOT NULL,
		url VARCHAR(100) NOT NULL,
		active INT NOT NULL
	)
END