IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'enrollment')
BEGIN
    CREATE TABLE enrollment
	(
		enrollmentID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		courseID INT NOT NULL,
		calendarID INT NOT NULL,
		studentID INT NOT NULL,
	)
END