IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'module')
BEGIN
    CREATE TABLE module
	(
		moduleID  INT IDENTITY(1,1) PRIMARY KEY,
		divisionID INT NOT NULL,
		name VARCHAR(50) NOT NULL,
		title VARCHAR(100) NOT NULL,
		url VARCHAR(100) NOT NULL,
		active INT NOT NULL
	)
END