IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'person')
BEGIN
    CREATE TABLE person
	(
		personID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		accountID INT NOT NULL,
		addressID INT NOT NULL,
		lastName VARCHAR(50) NOT NULL,
		firstName VARCHAR(50) NOT NULL,
		middleName VARCHAR(50) NOT NULL,
		suffix VARCHAR(4) NOT NULL,
		gender VARCHAR(5) NOT NULL,
		birthDate DATE NOT NULL,
		[language] VARCHAR(15) NOT NULL,
		ethinicity VARCHAR(20) NOT NULL
	)
END