IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Student')
BEGIN
    CREATE TABLE student
	(
		studentID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		personID INT NOT NULL,
		accountID INT NOT NULL
	)
END

