IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'subject')
BEGIN
    CREATE TABLE [subject]
	(
		subjectID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		calendarID INT NOT NULL,
		name VARCHAR(50) NOT NULL
	)
END