IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'usergroups')
BEGIN
    CREATE TABLE usergroups
	(
		usergroupID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		name VARCHAR(50) NOT NULL,
		[default] BIT NOT NULL,
		active BIT NOT NULL
	)
END

