IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Address')
BEGIN
    CREATE TABLE address
	(
		addressID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		personID INT NOT NULL,
		name VARCHAR(50) NOT NULL,
		city VARCHAR(50) NOT NULL,
		state VARCHAR(2) NOT NULL,
		street VARCHAR(100) NOT NULL,
		zip INT NOT NULL,
		phone INT NOT NULL,
		email VARCHAR(50) NOT NULL,
		
	)
END